# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /blog/:title
relative_permalinks: false

# Setup
title:               Kenix
tagline:             The Perfect Prey
url:                 http://kenix.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mike Zhao
  url:               https://twitter.com/bluepinme
  email:             zhongda.zhao@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/kenix/kenix.github.io

# Page list
pages_list:       
  About: '/about'
  Archive: '/archive'
